import Solutions.PolynomialPortalCutCounterexample

open Set HirschRegionRoute

namespace HirschPortalCycle

/-- Cyclic adjacency expressed without modular arithmetic, including both
orientations of the wrap edge. -/
def cycleAdj (n : ℕ) (x y : Fin n) : Prop :=
  x.val + 1 = y.val ∨ y.val + 1 = x.val ∨
    (x.val + 1 = n ∧ y.val = 0) ∨ (y.val + 1 = n ∧ x.val = 0)

/-- Distance-to-zero potential on a cycle. -/
def height {n : ℕ} (x : Fin n) : ℕ := min x.val (n - x.val)

lemma height_step {n : ℕ} {x y : Fin n} (h : cycleAdj n x y) :
    height y ≤ height x + 1 := by
  have hx := x.isLt
  have hy := y.isLt
  rcases h with hf | hb | ⟨hxEnd, hyZero⟩ | ⟨hyEnd, hxZero⟩
  · dsimp [height]
    by_cases hleft : x.val ≤ n - x.val
    · rw [Nat.min_eq_left hleft]
      exact (Nat.min_le_left y.val (n - y.val)).trans (by omega)
    · rw [Nat.min_eq_right (by omega : n - x.val ≤ x.val)]
      exact (Nat.min_le_right y.val (n - y.val)).trans (by omega)
  · dsimp [height]
    by_cases hleft : x.val ≤ n - x.val
    · rw [Nat.min_eq_left hleft]
      exact (Nat.min_le_left y.val (n - y.val)).trans (by omega)
    · rw [Nat.min_eq_right (by omega : n - x.val ≤ x.val)]
      exact (Nat.min_le_right y.val (n - y.val)).trans (by omega)
  · simp [height, hyZero]
  · have htail : n - y.val = 1 := by omega
    simpa [height, hxZero, htail] using Nat.min_le_right y.val 1

/-- The potential is 1-Lipschitz along every padded graph route. -/
theorem route_height_bound {n B : ℕ} {u v : Fin n}
    (hr : Route (cycleAdj n) B u v) : height v ≤ height u + B := by
  obtain ⟨w, hw0, hwB, hs⟩ := hr
  have hbound : ∀ k, k ≤ B → height (w k) ≤ height u + k := by
    intro k
    induction k with
    | zero =>
        intro _
        simp [hw0]
    | succ k ih =>
        intro hkB
        have hk := ih (by omega)
        have hstep : height (w (k + 1)) ≤ height (w k) + 1 := by
          rcases hs k (by omega) with heq | hadj
          · rw [← heq]
            omega
          · exact height_step hadj
        omega
  simpa only [hwB] using hbound B (Nat.le_refl B)

/-- Antipodal vertices of a 2m-cycle require at least m steps. -/
theorem even_cycle_lower_bound {m B : ℕ} (hm : 0 < m)
    (hr : Route (cycleAdj (2 * m)) B
      (⟨0, by omega⟩ : Fin (2 * m)) ⟨m, by omega⟩) : m ≤ B := by
  have h := route_height_bound hr
  have hsub : 2 * m - m = m := by omega
  simpa [height, hsub] using h

/-- The matching length-m route follows the forward half of the cycle. -/
theorem even_cycle_route {m : ℕ} (hm : 0 < m) :
    Route (cycleAdj (2 * m)) m
      (⟨0, by omega⟩ : Fin (2 * m)) ⟨m, by omega⟩ := by
  let w : ℕ → Fin (2 * m) := fun k =>
    ⟨min k m, (Nat.min_le_right k m).trans_lt (by omega)⟩
  refine ⟨w, ?_, ?_, ?_⟩
  · apply Fin.ext
    simp [w]
  · apply Fin.ext
    simp [w]
  · intro k hk
    right
    left
    change min k m + 1 = min (k + 1) m
    rw [Nat.min_eq_left (by omega : k ≤ m),
      Nat.min_eq_left (by omega : k + 1 ≤ m)]

/-- There is no constant repair bound based only on old length three and
two unit-cost endpoint regions when orderedness is replaced by temporal
interval overlap. The two damage intervals are [0,2) and [1,3), covering
all old step indices. This is a graph theorem, not a claim that the sequence
is generated by any particular projective-removal procedure. -/
theorem crossing_regions_unbounded (m : ℕ) (hm : 3 ≤ m) :
    ∃ S : Fin 2 → Set (Fin (2 * m)), ∃ w : ℕ → Fin (2 * m),
      (∀ i, ∀ x ∈ S i, ∀ y ∈ S i, Route (cycleAdj (2 * m)) 1 x y) ∧
      w 0 ∈ S 0 ∧ w 2 ∈ S 0 ∧ w 1 ∈ S 1 ∧ w 3 ∈ S 1 ∧
      Disjoint (S 0) (S 1) ∧
      (∀ B, Route (cycleAdj (2 * m)) B (w 0) (w 3) → m ≤ B) ∧
      Route (cycleAdj (2 * m)) m (w 0) (w 3) := by
  let z : Fin (2 * m) := ⟨0, by omega⟩
  let a : Fin (2 * m) := ⟨1, by omega⟩
  let b : Fin (2 * m) := ⟨m - 1, by omega⟩
  let t : Fin (2 * m) := ⟨m, by omega⟩
  let S : Fin 2 → Set (Fin (2 * m)) := fun i => if i = 0 then {z, a} else {b, t}
  let w : ℕ → Fin (2 * m) := fun k =>
    if k = 0 then z else if k = 1 then b else if k = 2 then a else t
  refine ⟨S, w, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · intro i
    fin_cases i
    · change ∀ x ∈ ({z, a} : Set (Fin (2 * m))),
        ∀ y ∈ ({z, a} : Set (Fin (2 * m))), Route (cycleAdj (2 * m)) 1 x y
      exact pair_region (cycleAdj (2 * m)) z a (Or.inl rfl) (Or.inr (Or.inl rfl))
    · change ∀ x ∈ ({b, t} : Set (Fin (2 * m))),
        ∀ y ∈ ({b, t} : Set (Fin (2 * m))), Route (cycleAdj (2 * m)) 1 x y
      have hbt : b.val + 1 = t.val := by dsimp [b, t]; omega
      exact pair_region (cycleAdj (2 * m)) b t (Or.inl hbt) (Or.inr (Or.inl hbt))
  · simp [S, w]
  · simp [S, w]
  · simp [S, w]
  · simp [S, w]
  · rw [Set.disjoint_left]
    intro x hx hy
    change x ∈ ({z, a} : Set (Fin (2 * m))) at hx
    change x ∈ ({b, t} : Set (Fin (2 * m))) at hy
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx hy
    rcases hx with hx | hx <;> rcases hy with hy | hy
    all_goals
      have heq := congrArg Fin.val (hx.symm.trans hy)
      dsimp [z, a, b, t] at heq
      omega
  · intro B hr
    exact even_cycle_lower_bound (by omega : 0 < m) hr
  · exact even_cycle_route (by omega : 0 < m)

#print axioms height_step
#print axioms route_height_bound
#print axioms even_cycle_lower_bound
#print axioms even_cycle_route
#print axioms crossing_regions_unbounded

end HirschPortalCycle
