import Mathlib
import Definitions.Def_Hirsch_model
import Solutions.PolynomialLogLocalRankReduction
import Solutions.PolynomialExcessFaceRank

open scoped RealInnerProductSpace
open Set Hirsch

set_option maxHeartbeats 3000000

noncomputable section

namespace HirschLogRank

variable {d n : ℕ}

/-- The canonical active-neutral span can never have rank larger than the
ambient dimension. -/
lemma activeNeutralSpan_finrank_le_dim
    (a : Fin n → EuclideanSpace ℝ (Fin d)) (b : Fin n → ℝ)
    (u v x : EuclideanSpace ℝ (Fin d)) :
    Module.finrank ℝ (activeNeutralSpan a b u v x) ≤ d := by
  calc
    Module.finrank ℝ (activeNeutralSpan a b u v x) ≤
        Module.finrank ℝ (EuclideanSpace ℝ (Fin d)) :=
      Submodule.finrank_le (activeNeutralSpan a b u v x)
    _ = d := finrank_euclideanSpace_fin (𝕜 := ℝ)

/-- The canonical active-neutral span is generated by a subset of the global
neutral rows, so its rank is at most the number of global neutral rows. -/
lemma activeNeutralSpan_finrank_le_neutral_card
    (a : Fin n → EuclideanSpace ℝ (Fin d)) (b : Fin n → ℝ)
    (u v x : EuclideanSpace ℝ (Fin d)) :
    Module.finrank ℝ (activeNeutralSpan a b u v x) ≤
      (HirschPolynomialAccess.neutralRows a b u v).card := by
  classical
  let T : Set (Fin n) := {i : Fin n |
    a i ≠ 0 ∧ ⟪a i, u⟫ ≠ b i ∧ ⟪a i, v⟫ ≠ b i ∧ ⟪a i, x⟫ = b i}
  let S : Set (EuclideanSpace ℝ (Fin d)) := a '' T
  have hTfin : T.Finite := Set.toFinite T
  have hSfin : S.Finite := hTfin.image a
  letI : Fintype T := hTfin.fintype
  letI : Fintype S := hSfin.fintype
  have hspan : Module.finrank ℝ (Submodule.span ℝ S) ≤ S.toFinset.card :=
    finrank_span_le_card S
  have himage : S.toFinset.card ≤ T.toFinset.card := by
    rw [Set.toFinset_image]
    exact Finset.card_image_le
  have hsubset : T.toFinset ⊆ HirschPolynomialAccess.neutralRows a b u v := by
    intro i hi
    have hiT : i ∈ T := by simpa using hi
    dsimp [T] at hiT
    simp [HirschPolynomialAccess.neutralRows, hiT.1, hiT.2.1, hiT.2.2.1]
  have hcard : T.toFinset.card ≤
      (HirschPolynomialAccess.neutralRows a b u v).card :=
    Finset.card_le_card hsubset
  calc
    Module.finrank ℝ (activeNeutralSpan a b u v x) =
        Module.finrank ℝ (Submodule.span ℝ S) := by
      rfl
    _ ≤ S.toFinset.card := hspan
    _ ≤ T.toFinset.card := himage
    _ ≤ (HirschPolynomialAccess.neutralRows a b u v).card := hcard

/-- Under endpoint separation, every logarithmically-large local-rank witness
lies automatically in BOTH older hard regimes: ambient Larman is not already
polynomial, and the global neutral-row excess estimate is not already
polynomial. Hence the logarithmic local-rank obstruction strictly refines the
previous double-hard numerical reduction. -/
theorem large_local_neutral_rank_implies_double_hard
    (a : Fin n → EuclideanSpace ℝ (Fin d)) (b : Fin n → ℝ)
    (u v x : EuclideanSpace ℝ (Fin d))
    (hu : u ∈ extremePoints ℝ (Hpoly a b))
    (hv : v ∈ extremePoints ℝ (Hpoly a b))
    (hsep : ∀ i, a i ≠ 0 →
      ⟪a i, u⟫ ≠ b i ∨ ⟪a i, v⟫ ≠ b i)
    (hlarge : Nat.log 2 (n + d) + 3 <
      Module.finrank ℝ (activeNeutralSpan a b u v x)) :
    n < 2 ^ (d - 3) ∧ n < 2 ^ ((n - 2 * d) - 3) := by
  let N : ℕ := n + d
  have hdim : Module.finrank ℝ (activeNeutralSpan a b u v x) ≤ d :=
    activeNeutralSpan_finrank_le_dim a b u v x
  have hlogd : Nat.log 2 N + 3 < d := by
    dsimp [N]
    exact hlarge.trans_le hdim
  have hdpos : 0 < d := by omega
  have hNpos : 0 < N := by
    dsimp [N]
    omega
  have hNpow : N < 2 ^ (Nat.log 2 N + 1) :=
    Nat.lt_pow_succ_log_self (by omega : 1 < 2) N
  have hexpD : Nat.log 2 N + 1 ≤ d - 3 := by omega
  have hpowD : 2 ^ (Nat.log 2 N + 1) ≤ 2 ^ (d - 3) :=
    Nat.pow_le_pow_right (by omega : 0 < 2) hexpD
  have hambientN : N < 2 ^ (d - 3) := hNpow.trans_le hpowD
  have hnN : n ≤ N := by
    dsimp [N]
    omega
  have hambient : n < 2 ^ (d - 3) := hnN.trans_lt hambientN

  have hneutral : Module.finrank ℝ (activeNeutralSpan a b u v x) ≤
      (HirschPolynomialAccess.neutralRows a b u v).card :=
    activeNeutralSpan_finrank_le_neutral_card a b u v x
  have hexcessCard : (HirschPolynomialAccess.neutralRows a b u v).card ≤
      n - 2 * d :=
    HirschPolynomialAccess.neutral_card_le_excess a b u v hu hv hsep
  have hlogE : Nat.log 2 N + 3 < n - 2 * d :=
    hlarge.trans_le (hneutral.trans hexcessCard)
  have hexpE : Nat.log 2 N + 1 ≤ (n - 2 * d) - 3 := by omega
  have hpowE : 2 ^ (Nat.log 2 N + 1) ≤ 2 ^ ((n - 2 * d) - 3) :=
    Nat.pow_le_pow_right (by omega : 0 < 2) hexpE
  have hexcessN : N < 2 ^ ((n - 2 * d) - 3) := hNpow.trans_le hpowE
  have hexcess : n < 2 ^ ((n - 2 * d) - 3) := hnN.trans_lt hexcessN
  exact ⟨hambient, hexcess⟩

#print axioms activeNeutralSpan_finrank_le_dim
#print axioms activeNeutralSpan_finrank_le_neutral_card
#print axioms large_local_neutral_rank_implies_double_hard

end HirschLogRank
